name: alexandrio
description: The alexandrio.cloud Flutter application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.1.0
  intl: ^0.17.0

  amberkit:
    git: https://github.com/williambulin/amberkit.git
    # path: ../../williambulin/amberkit
  dart_downloader:
    git: https://github.com/williambulin/dart_downloader.git
  flutter_pdf_parser:
    # git: https://github.com/alexandr-io/flutter_pdf_parser
    path: ../flutter_pdf_parser
  flutter_epub_reader:
    # git: https://github.com/alexandr-io/flutter_epub_reader
    path: ../flutter_epub_reader

  collection: ^1.15.0
  version: ^2.0.0
  file_picker_cross: ^4.4.2
  package_info_plus: ^1.0.6
  url_launcher: ^6.0.10
  sentry_flutter: ^6.0.1

  # url_launcher: ^6.0.6
  # webview_flutter: ^2.0.8
  # file_picker: ^3.0.2+2
  # dio: ^4.0.0
  # flutter_local_notifications: ^6.0.0
  # device_info_plus: ^1.0.1
  # package_info: ^2.0.2
  # path_provider: ^2.0.2
  # open_file: ^3.2.1
  # dart_downloader:
    # git: https://github.com/williambulin/dart_downloader.git


dev_dependencies:
  pedantic: ^1.11.0
  flutter_lints: ^1.0.3
  hive_generator: ^1.1.0
  build_runner: ^2.0.4
  flutter_appicon_generator:
    git: https://github.com/williambulin/flutter_appicon_generator # flutter pub run flutter_appicon_generator:main

flutter:
  uses-material-design: true
  generate: true

icons:
  path: "assets/logo.png"
  background: "assets/logo-background.png"
  foreground: "assets/logo-foreground.png"
