on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: ["Android", "Windows", "Linux", "macOS", "iOS"]
        include:
          - target: Android
            os: ubuntu-latest
          - target: Windows
            os: windows-latest
          - target: Linux
            os: ubuntu-latest
          - target: macOS
            os: macos-latest
          - target: iOS
            os: macos-latest

    name: ${{matrix.target}}
    runs-on: ${{matrix.os}}

    steps:
      - name: Set up sed
        if: matrix.os != 'macos-latest'
        run: echo "sed=sed" >> $GITHUB_ENV

      - name: Set up sed for macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install gnu-sed
          echo "sed=gsed" >> $GITHUB_ENV

      - name: Checking out sigining keys
        uses: actions/checkout@v2
        if: matrix.target == 'Android' && github.repository_owner == 'alexandr-io'
        with:
          repository: alexandr-io/signingkeys
          token: ${{secrets.GHKEY}}
          path: signingkeys

      - name: Checking out epub library source code
        uses: actions/checkout@v2
        with:
          repository: alexandr-io/flutter_epub_reader
          path: flutter_epub_reader

      - name: Checking out pdf library source code
        uses: actions/checkout@v2
        with:
          repository: alexandr-io/flutter_pdf_parser
          path: flutter_pdf_parser

      - name: Checking out Alexandrio source code
        uses: actions/checkout@v2
        with:
          path: alexandrio

      - name: Setting up Java
        if: matrix.target == 'Android'
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Checking out Flutter
        uses: chatsen/flutter-action@master
        with:
          channel: "master"

      - name: Changing version number and build number to the Github Tag
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ./alexandrio
        run: |
          ${{env.sed}} -i "s/^version: .*$/version: ${GITHUB_REF/refs\/tags\//}/" ./pubspec.yaml
          cat ./pubspec.yaml

      - name: Check for flutter updates
        run: flutter upgrade

      - name: Patch a fix for gifs inside the Flutter framework
        run: |
          ${{env.sed}} -i '/_frameDuration = _nextFrame!.duration;/a \ \ \ \ \ \ if (_frameDuration!.inMilliseconds <= 10) _frameDuration = Duration(milliseconds: 100);' $(which flutter | head -n 1 | ${{env.sed}} -e 's/\\/\//g' -e 's/\/bin\/flutter.*//')/packages/flutter/lib/src/painting/image_stream.dart

      - name: Create project for Android
        working-directory: ./alexandrio
        if: matrix.target == 'Android'
        run: |
          flutter create --platforms android,ios --org com.alexandrio .
          # Allow building with a WebView on older platforms        # ${{env.sed}} -i 's/minSdkVersion 16/minSdkVersion 19/' ./android/app/build.gradle
          ${{env.sed}} -i '/<\/manifest>/i \ \ \ \ <uses-sdk tools:overrideLibrary="io.flutter.plugins.webviewflutter"/>' ./android/app/src/main/AndroidManifest.xml
          ${{env.sed}} -i '/.*package=".*".*/i \ \ \ \ xmlns:tools="http://schemas.android.com/tools"' ./android/app/src/main/AndroidManifest.xml
          # Change the app title
          ${{env.sed}} -i 's/android:label=".*"/android:label="Alexandrio"/' ./android/app/src/main/AndroidManifest.xml
          # Add Internet permission
          ${{env.sed}} -i '/.*package=".*".*/a \ \ \ <uses-permission android:name="android.permission.INTERNET"/>' ./android/app/src/main/AndroidManifest.xml
          # Fix for some 3rd party libraries
          ${{env.sed}} -i '/.*release {.*/a \ \ \ \ \ \ \ \ \ \ \ \ shrinkResources false\n\ \ \ \ \ \ \ \ \ \ \ \ minifyEnabled false' ./android/app/build.gradle
          # Add support for drawing behind the navbar on Android 11+
          ${{env.sed}} -i "/io.flutter.embedding.android.FlutterActivity/a import android.os.Bundle\nimport android.os.Build\nimport androidx.annotation.NonNull\nimport io.flutter.embedding.android.FlutterActivityLaunchConfigs.BackgroundMode.transparent\nimport io.flutter.embedding.engine.FlutterEngine\nimport io.flutter.plugins.GeneratedPluginRegistrant" android/app/src/main/kotlin/com/alexandrio/alexandrio/MainActivity.kt
          ${{env.sed}} -i "/FlutterActivity()/a \ \ \ \ override fun onCreate(savedInstanceState: Bundle?) {\n\ \ \ \ \ \ \ \ super.onCreate(savedInstanceState)\n\ \ \ \ \ \ \ \ if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {\n\ \ \ \ \ \ \ \ \ \ \ \ window.setDecorFitsSystemWindows(false)\n\ \ \ \ \ \ \ \ }\n\ \ \ \ }" android/app/src/main/kotlin/com/alexandrio/alexandrio/MainActivity.kt
          
      - name: Add signing to the project for Android
        working-directory: ./alexandrio
        if: matrix.target == 'Android' && github.repository_owner == 'alexandr-io'
        run: |
          # Signing profile
          ${{env.sed}} -i '/android {/i def keystoreProperties = new Properties()\ndef keystorePropertiesFile = rootProject.file('\''../../signingkeys/key.properties'\'')\nif (keystorePropertiesFile.exists()) {\n    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))\n}\n' ./android/app/build.gradle
          ${{env.sed}} -i '/.*buildTypes {/i \ \ \ \ signingConfigs {\n\ \ \ \ \ \ \ \ release {\n\ \ \ \ \ \ \ \ \ \ \ \ keyAlias keystoreProperties['\''keyAlias'\'']\n\ \ \ \ \ \ \ \ \ \ \ \ keyPassword keystoreProperties['\''keyPassword'\'']\n\ \ \ \ \ \ \ \ \ \ \ \ storeFile keystoreProperties['\''storeFile'\''] ? file(keystoreProperties['\''storeFile'\'']) : null\n\ \ \ \ \ \ \ \ \ \ \ \ storePassword keystoreProperties['\''storePassword'\'']\n\ \ \ \ \ \ \ \ }\n\ \ \ \ }' ./android/app/build.gradle
          ${{env.sed}} -i 's/signingConfig signingConfigs.debug/signingConfig signingConfigs.release/' ./android/app/build.gradle

      - name: Create project for iOS
        working-directory: ./alexandrio
        if: matrix.target == 'iOS'
        run: |
          flutter create --platforms ios,android --org com.alexandrio .
          # Add notification support on the native side
          ${{env.sed}} -i '/-> Bool {/a \ \ \ \ if #available(iOS 10.0, *) {\ \ \ \ \ \ UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate\ \ \ \ }' ./ios/Runner/AppDelegate.swift
          # Change the app title
          ${{env.sed}} -i 's/<string>alexandrio<\/string>/<string>Alexandrio<\/string>/' ./ios/Runner/Info.plist
          # Background modes
          ${{env.sed}} -i '/<dict>/a \ \ <key>UIBackgroundModes</key>\n\ \ <array>\n\ \ \ \ <string>audio</string>\n\ \ </array>' ios/Runner/Info.plist
          # Library usage description
          ${{env.sed}} -i '/<dict>/a \ \ <key>NSPhotoLibraryUsageDescription</key>\n\ \ <string>Alexandrio requests to access your files to allow file selection.</string>' ios/Runner/Info.plist

      - name: Create project for Windows
        working-directory: ./alexandrio
        if: matrix.target == 'Windows'
        run: |
          flutter config --enable-windows-desktop
          flutter create --platforms windows --org com.alexandrio .

      - name: Create project for Linux
        working-directory: ./alexandrio
        if: matrix.target == 'Linux'
        run: |
          flutter config --enable-linux-desktop
          flutter create --platforms linux --org com.alexandrio .

      - name: Create project for macOS
        working-directory: ./alexandrio
        if: matrix.target == 'macOS'
        run: |
          flutter config --enable-macos-desktop
          flutter create --platforms macos --org com.alexandrio .

      - name: Cleaning up the test directory
        working-directory: ./alexandrio
        run: rm -rf test

      # - name: Building the launcher icon
      #   working-directory: ./alexandrio
      #   if: matrix.target == 'Android' || matrix.target == 'iOS'
      #   run: flutter pub run flutter_launcher_icons:main

      - name: Build on Android
        if: matrix.target == 'Android'
        working-directory: ./alexandrio
        run: flutter build apk

      - name: Build on iOS
        if: matrix.target == 'iOS'
        working-directory: ./alexandrio
        run: flutter build ios --no-codesign

      - name: Build on Windows
        if: matrix.target == 'Windows'
        working-directory: ./alexandrio
        run: flutter build windows
        
      - name: Build on Linux
        if: matrix.target == 'Linux'
        working-directory: ./alexandrio
        run: |
          sudo apt install libgtk-3-dev ninja-build
          flutter build linux

      - name: Build on macOS
        if: matrix.target == 'macOS'
        working-directory: ./alexandrio
        run: flutter build macos

      # iOS release
      - name: Preparing iOS release and converting .app to .ipa
        if: matrix.target == 'iOS'
        run: |
          mkdir -p release/Payload
          cp -rf ./alexandrio/build/ios/iphoneos/Runner.app ./release/Payload/Runner.app
          ditto -c -k --sequesterRsrc --keepParent ./release/Payload ./release/iOS.ipa
      
      - name: Uploading iOS artifact
        if: matrix.target == 'iOS'
        uses: actions/upload-artifact@v2
        with:
          name: iOS.ipa
          path: ./release/iOS.ipa

      - name: Uploading iOS tagged release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && matrix.target == 'iOS' && github.repository_owner == 'alexandr-io'
        with:
          files: ./release/iOS.ipa
        env:
          GITHUB_TOKEN: ${{secrets.GHKEY}}

      # Android release
      - name: Preparing Android release
        if: matrix.target == 'Android'
        run: |
          mkdir release
          cp ./alexandrio/build/app/outputs/flutter-apk/app-release.apk ./release/Android.apk

      - name: Uploading Android artifact
        if: matrix.target == 'Android'
        uses: actions/upload-artifact@v2
        with:
          name: Android.apk
          path: ./release/Android.apk

      - name: Uploading Android tagged release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && matrix.target == 'Android' && github.repository_owner == 'alexandr-io'
        with:
          files: ./release/Android.apk
        env:
          GITHUB_TOKEN: ${{secrets.GHKEY}}